const fs = require('fs');
const path = require('path');

const filePath = path.join(
  'C:\\Projects\\materialespro-enterprise-v10\\materialespro-enterprise-v10\\whatsapp-bot-gdl',
  'import_local_directo.js'
);

const lines = [
  "// import_local_directo.js — MaterialesPro GDL",
  "// Importa catalogo_MASTER directamente a Supabase desde local",
  "// Bypass completo de Render (sin timeout)",
  "// Comando: node import_local_directo.js",
  "//",
  "// PRECIOS: todos son NETO — precio_venta=Precio1NETO, precio_lista=PrecioListaNETO",
  "",
  "require('dotenv').config();",
  "const XLSX = require('xlsx');",
  "const { Pool } = require('pg');",
  "const fs   = require('fs');",
  "const path = require('path');",
  "",
  "// ── Ruta al Excel ────────────────────────────────────────────────────────",
  "const EXCEL_PATH   = path.join(__dirname, 'plantilla_catalogo_v2 (1).xlsx');",
  "const CATALOG_PATH = path.join(__dirname, 'catalogo.json');",
  "",
  "const pool = new Pool({ connectionString: process.env.DATABASE_URL });",
  "",
  "// ── Helpers ──────────────────────────────────────────────────────────────",
  "function getVal(r) {",
  "  var keys = Array.prototype.slice.call(arguments, 1);",
  "  for (var i = 0; i < keys.length; i++) {",
  "    if (r[keys[i]] !== undefined && r[keys[i]] !== '') return r[keys[i]];",
  "  }",
  "  return '';",
  "}",
  "",
  "// parsePrecio: limpia comas de miles antes de parsear",
  "// Ejemplo: '2,990.00' → 2990.00  |  '85,225.47' → 85225.47",
  "function parsePrecio(v) {",
  "  if (!v && v !== 0) return 0;",
  "  return parseFloat(String(v).replace(/,/g, '').replace(/[^0-9.]/g, '')) || 0;",
  "}",
  "",
  "function parseActivo(v) {",
  "  if (v === true || v === 1) return true;",
  "  var s = String(v).toLowerCase().trim();",
  "  return s === 'verdadero' || s === 'true' || s === '1';",
  "}",
  "",
  "function limpiar(v) {",
  "  return String(v || '').trim() || null;",
  "}",
  "",
  "// ── Main ─────────────────────────────────────────────────────────────────",
  "async function main() {",
  "  console.log('\\n================================================');",
  "  console.log('  MaterialesPro — Import Local Directo a Supabase');",
  "  console.log('================================================\\n');",
  "",
  "  if (!fs.existsSync(EXCEL_PATH)) {",
  "    console.error('No se encontro: ' + EXCEL_PATH);",
  "    console.error('Verifica que el archivo Excel esta en la raiz del proyecto');",
  "    process.exit(1);",
  "  }",
  "",
  "  // 1. Leer Excel",
  "  console.log('Leyendo: ' + EXCEL_PATH);",
  "  var wb    = XLSX.readFile(EXCEL_PATH);",
  "  var sheet = wb.Sheets[wb.SheetNames[0]];",
  "  var rows  = XLSX.utils.sheet_to_json(sheet, { defval: '' });",
  "  console.log('   Filas en Excel: ' + rows.length);",
  "",
  "  // 2. Parsear productos",
  "  var productos = rows.map(function(r, i) {",
  "    var nombre = String(getVal(r, 'Articulo', 'Artículo', 'nombre') || '').trim();",
  "    if (!nombre) return null;",
  "    if (nombre.startsWith('\\u2192') || nombre.startsWith('VERDE')) return null;",
  "",
  "    // Categoria: trim() para quitar trailing spaces, fallback 'General'",
  "    var categoria = limpiar(getVal(r, 'Categoria', 'Categoría', 'categoria'));",
  "    if (!categoria || !categoria.trim()) categoria = 'General';",
  "    else categoria = categoria.trim();",
  "",
  "    return {",
  "      codigo:                    String(getVal(r, 'Código CRM', 'Codigo CRM', 'id') || '').trim() || ('PROD-' + String(i+1).padStart(3,'0')),",
  "      nombre:                    nombre,",
  "      descripcion:               limpiar(getVal(r, 'descripcion', 'Descripcion')),",
  "      categoria:                 categoria,",
  "      marca:                     limpiar(getVal(r, 'Marca', 'marca')),",
  "      presentacion:              limpiar(getVal(r, 'Presentacion', 'Presentación', 'presentacion')),",
  "      unidad_medida:             limpiar(getVal(r, 'Unidad medida', 'unidad')) || 'pza',",
  "      cantidad:                  parseFloat(getVal(r, 'Contenido', 'cantidad') || 0) || null,",
  "      cantidad_minima:           parseFloat(getVal(r, 'Cantidad minima', 'Cantidad mínima', 'cantidad_minima') || 0) || null,",
  "      // PRECIOS — todos NETO",
  "      precio_venta:              parsePrecio(getVal(r, 'Precio 1 NETO', 'precio_venta', 'precio')) || null,",
  "      precio_lista:              parsePrecio(getVal(r, 'Precio lista', 'precio_lista')) || null,",
  "      precio_2:                  parsePrecio(getVal(r, 'Precio 2 NETO', 'precio_2')) || null,",
  "      precio_3:                  parsePrecio(getVal(r, 'Precio 3 NETO', 'precio_3')) || null,",
  "      precio_4:                  parsePrecio(getVal(r, 'Precio 4 NETO', 'precio_4')) || null,",
  "      iva:                       parsePrecio(getVal(r, 'IVA', 'iva')) || null,",
  "      costo_neto:                parsePrecio(getVal(r, 'Costo NETO', 'costo_neto', 'costo')) || null,",
  "      descuento_maximo:          parsePrecio(getVal(r, 'Descuento maximo', 'Descuento máximo', 'descuento_maximo')) || null,",
  "      rendimiento_m2_por_unidad: parseFloat(getVal(r, 'rendimiento_m2_por_unidad') || 0) || null,",
  "      rendimiento_nota:          limpiar(getVal(r, 'rendimiento_nota')),",
  "      unidades_pallet:           parseInt(getVal(r, 'Unidades pallet', 'unidades_pallet') || 0) || null,",
  "      moneda:                    limpiar(getVal(r, 'Moneda', 'moneda')) || 'MXN',",
  "      fecha_precio:              getVal(r, 'Fecha precio', 'fecha_precio') || null,",
  "      version_precio:            limpiar(getVal(r, 'Version', 'Versión', 'version')),",
  "      activo:                    parseActivo(getVal(r, 'Activo', 'activo')),",
  "    };",
  "  }).filter(Boolean);",
  "",
  "  console.log('   Productos validos parseados: ' + productos.length);",
  "",
  "  // Resumen por marca",
  "  var marcas = {};",
  "  productos.forEach(function(p) {",
  "    var m = p.marca || 'SIN_MARCA';",
  "    marcas[m] = (marcas[m] || 0) + 1;",
  "  });",
  "  console.log('\\n   Por marca:');",
  "  Object.entries(marcas).sort().forEach(function(entry) {",
  "    console.log('     ' + entry[0] + ': ' + entry[1]);",
  "  });",
  "",
  "  if (!productos.length) {",
  "    console.error('\\nSin productos validos. Verificar columnas del Excel.');",
  "    process.exit(1);",
  "  }",
  "",
  "  // 3. UPSERT a DB",
  "  console.log('\\nIniciando UPSERT a Supabase...');",
  "  var client = await pool.connect();",
  "  var insertados = 0, actualizados = 0, errores = 0;",
  "  var BATCH = 50;",
  "",
  "  try {",
  "    for (var i = 0; i < productos.length; i++) {",
  "      var p = productos[i];",
  "      try {",
  "        var r = await client.query(",
  "          'INSERT INTO catalogo_productos (' +",
  "          '  codigo, nombre, descripcion, categoria, marca,' +",
  "          '  presentacion, unidad_medida, cantidad, cantidad_minima,' +",
  "          '  precio_venta, precio_lista, precio_2, precio_3, precio_4,' +",
  "          '  iva, costo_neto, descuento_maximo,' +",
  "          '  rendimiento_m2_por_unidad, rendimiento_nota,' +",
  "          '  unidades_pallet, moneda, fecha_precio, version_precio,' +",
  "          '  activo, updated_at' +",
  "          ') VALUES (' +",
  "          '  $1,$2,$3,$4,$5,$6,$7,$8,$9,' +",
  "          '  $10,$11,$12,$13,$14,$15,$16,$17,$18,$19,' +",
  "          '  $20,$21,$22,$23,$24,NOW()' +",
  "          ') ON CONFLICT (codigo) DO UPDATE SET' +",
  "          '  nombre=$2, descripcion=$3, categoria=$4, marca=$5,' +",
  "          '  presentacion=$6, unidad_medida=$7, cantidad=$8, cantidad_minima=$9,' +",
  "          '  precio_venta=$10, precio_lista=$11, precio_2=$12, precio_3=$13, precio_4=$14,' +",
  "          '  iva=$15, costo_neto=$16, descuento_maximo=$17,' +",
  "          '  rendimiento_m2_por_unidad=$18, rendimiento_nota=$19,' +",
  "          '  unidades_pallet=$20, moneda=$21, fecha_precio=$22, version_precio=$23,' +",
  "          '  activo=$24, updated_at=NOW()' +",
  "          ' RETURNING (xmax = 0) AS fue_insert',",
  "          [",
  "            p.codigo, p.nombre, p.descripcion, p.categoria, p.marca,",
  "            p.presentacion, p.unidad_medida, p.cantidad, p.cantidad_minima,",
  "            p.precio_venta, p.precio_lista, p.precio_2, p.precio_3, p.precio_4,",
  "            p.iva, p.costo_neto, p.descuento_maximo,",
  "            p.rendimiento_m2_por_unidad, p.rendimiento_nota,",
  "            p.unidades_pallet, p.moneda, p.fecha_precio, p.version_precio,",
  "            p.activo",
  "          ]",
  "        );",
  "        if (r.rows[0] && r.rows[0].fue_insert) insertados++; else actualizados++;",
  "      } catch (err) {",
  "        errores++;",
  "        console.error('  Error ' + p.codigo + ': ' + err.message);",
  "      }",
  "      if ((i + 1) % BATCH === 0 || i === productos.length - 1) {",
  "        process.stdout.write('\\r   Procesados: ' + (i+1) + '/' + productos.length +",
  "          ' | +' + insertados + ' nuevos | ~' + actualizados + ' updates | x' + errores + ' errores');",
  "      }",
  "    }",
  "    console.log('\\n');",
  "",
  "    // 4. Sync inventario automatico",
  "    console.log('Sincronizando tabla inventario...');",
  "    var syncResult = await client.query(",
  "      'INSERT INTO inventario (catalogo_id, stock_physical, stock_reserved, stock_minimo) ' +",
  "      'SELECT id, 0, 0, 0 FROM catalogo_productos WHERE activo = true ' +",
  "      'ON CONFLICT (catalogo_id) DO NOTHING'",
  "    );",
  "    console.log('   Filas inventario sincronizadas: ' + syncResult.rowCount);",
  "",
  "    // 5. Contar por marca en DB",
  "    var countDB = await client.query(",
  "      'SELECT marca, COUNT(*) as total FROM catalogo_productos GROUP BY marca ORDER BY total DESC'",
  "    );",
  "    console.log('\\nDB despues del import:');",
  "    var total = 0;",
  "    countDB.rows.forEach(function(row) {",
  "      console.log('   ' + (row.marca || 'SIN_MARCA') + ': ' + row.total);",
  "      total += parseInt(row.total);",
  "    });",
  "    console.log('   TOTAL: ' + total + '\\n');",
  "",
  "    // 6. Regenerar catalogo.json",
  "    console.log('Regenerando catalogo.json...');",
  "    var allProds = await client.query(",
  "      'SELECT codigo, nombre, descripcion, categoria, marca,' +",
  "      '       presentacion, unidad_medida AS unidad, cantidad, cantidad_minima,' +",
  "      '       precio_venta, precio_lista,' +",
  "      '       precio_2, precio_3, precio_4,' +",
  "      '       iva, costo_neto, descuento_maximo,' +",
  "      '       rendimiento_m2_por_unidad, rendimiento_nota,' +",
  "      '       unidades_pallet, moneda, fecha_precio, version_precio,' +",
  "      '       activo, destacado, en_oferta, precio_oferta, oferta_hasta,' +",
  "      '       mas_vendido, orden_display' +",
  "      ' FROM catalogo_productos WHERE activo = true' +",
  "      ' ORDER BY categoria, marca, nombre'",
  "    );",
  "",
  "    var prods = allProds.rows.map(function(row) {",
  "      return {",
  "        id:                        row.codigo,",
  "        codigo:                    row.codigo,",
  "        nombre:                    row.nombre,",
  "        descripcion:               row.descripcion || '',",
  "        categoria:                 row.categoria || 'General',",
  "        marca:                     row.marca || '',",
  "        presentacion:              row.presentacion || '',",
  "        unidad:                    row.unidad || '',",
  "        cantidad:                  row.cantidad,",
  "        cantidad_minima:           row.cantidad_minima || 1,",
  "        precio:                    parseFloat(row.precio_venta) || 0,",
  "        precio_venta:              parseFloat(row.precio_venta) || 0,",
  "        precio_lista:              parseFloat(row.precio_lista) || 0,",
  "        precio_2:                  parseFloat(row.precio_2) || 0,",
  "        precio_3:                  parseFloat(row.precio_3) || 0,",
  "        precio_4:                  parseFloat(row.precio_4) || 0,",
  "        iva:                       parseFloat(row.iva) || 0,",
  "        costo_neto:                parseFloat(row.costo_neto) || 0,",
  "        descuento_maximo:          parseFloat(row.descuento_maximo) || 0,",
  "        rendimiento_m2_por_unidad: row.rendimiento_m2_por_unidad,",
  "        rendimiento_nota:          row.rendimiento_nota || '',",
  "        moneda:                    row.moneda || 'MXN',",
  "        activo:                    row.activo,",
  "        destacado:                 row.destacado || false,",
  "        en_oferta:                 row.en_oferta || false,",
  "        precio_oferta:             row.precio_oferta,",
  "        mas_vendido:               row.mas_vendido || false,",
  "        orden_display:             row.orden_display || 0,",
  "      };",
  "    });",
  "",
  "    var por_categoria = {};",
  "    prods.forEach(function(p) {",
  "      if (!por_categoria[p.categoria]) por_categoria[p.categoria] = [];",
  "      por_categoria[p.categoria].push(p.codigo);",
  "    });",
  "",
  "    var catalogo = {",
  "      meta: {",
  "        total_productos: prods.length,",
  "        categorias: Object.keys(por_categoria).length,",
  "        marcas: Array.from(new Set(prods.map(function(p) { return p.marca; }).filter(Boolean))).sort(),",
  "        moneda: 'MXN',",
  "        generado: new Date().toISOString(),",
  "        version: 'V4-SCHEMA-NUEVO'",
  "      },",
  "      productos: prods,",
  "      por_categoria: por_categoria,",
  "      indice: Object.fromEntries(prods.map(function(p) { return [p.codigo, p]; }))",
  "    };",
  "",
  "    if (fs.existsSync(CATALOG_PATH)) {",
  "      fs.copyFileSync(CATALOG_PATH, CATALOG_PATH + '.bak');",
  "    }",
  "    fs.writeFileSync(CATALOG_PATH, JSON.stringify(catalogo, null, 2), 'utf8');",
  "    var kb = Math.round(fs.statSync(CATALOG_PATH).size / 1024);",
  "    console.log('catalogo.json regenerado: ' + prods.length + ' productos (' + kb + ' KB)\\n');",
  "",
  "    console.log('================================================');",
  "    console.log('  Import completo');",
  "    console.log('     Nuevos:       ' + insertados);",
  "    console.log('     Actualizados: ' + actualizados);",
  "    console.log('     Errores:      ' + errores);",
  "    console.log('================================================');",
  "    console.log('\\nSIGUIENTE PASO:');",
  "    console.log('   git add catalogo.json');",
  "    console.log('   git commit -m \"fix: import catalogo schema nuevo ' + prods.length + ' productos\"');",
  "    console.log('   git push origin master\\n');",
  "",
  "  } finally {",
  "    client.release();",
  "    await pool.end();",
  "  }",
  "}",
  "",
  "main().catch(function(err) {",
  "  console.error('\\nError fatal:', err.message);",
  "  process.exit(1);",
  "});",
];

const newContent = lines.join('\n') + '\n';
fs.writeFileSync(filePath, newContent, { encoding: 'utf8' });
console.log('import_local_directo.js reescrito correctamente — ' + lines.length + ' lineas');
